spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/smsm_db
spring.datasource.username=smsm_user
spring.datasource.password=smsm_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false